### ISSUE TITLE
[BUG] Cores da aba Trendings

### ISSUE THREAD

**Issue by Suburbanno** [Nem-Tudo/betterbluesky_extension#1]
Acredito que seria interessante manter a cor que o usuário está usando. Ao mudar o tema, as coisas quebram.

ex:
Menos escuro
![image](https://github.com/user-attachments/assets/52c66b46-7dee-40ce-b5ef-c20270244973)

Claro
![image](https://github.com/user-attachments/assets/b391dfa1-4815-40df-bc52-bff56121c0d1)

Como poderia ser
![image](https://github.com/user-attachments/assets/710675df-dfc3-4779-b508-a298430d2915)

**Comment by Nem-Tudo** [comment]
Foi atualizado!
