### ISSUE TITLE
[BUG] Padding adicionado aos itens de navegação faz eles pularem

### ISSUE THREAD

**Issue by mbernardes19** [Nem-Tudo/betterbluesky_extension#2]
https://github.com/user-attachments/assets/d86908db-3575-4f74-93e4-618633ad7790

No site padrão isso não acontece:

https://github.com/user-attachments/assets/b31155e0-c77d-4c92-929e-5ce87d599161

**Comment by Nem-Tudo** [comment]
foi resolvido!
