### ISSUE TITLE
[FEATURE]  Melhoria no espaçamento e Também melhorar para saber que tem pra baixo

### ISSUE THREAD

**Issue by fabiohcnobre** [Nem-Tudo/betterbluesky_extension#4]
- Melhorar o espaçamento
- Colocar alguma coisa pra saber que tem coisa para baixo/a barra fica muito pequena nem da para perceber no modo escuro. 

![image](https://github.com/user-attachments/assets/a180b8a3-3e9f-44e0-855f-94166d1db433)

![image](https://github.com/user-attachments/assets/35dd7403-7a23-47d5-b0f9-55411b807165)

**Comment by Nem-Tudo** [comment]
Acho q deixar a barra branca resolve, o que acha?

**Comment by fabiohcnobre** [comment]
Sim acho que sim ajuda
