### ISSUE TITLE
Organização por números 

### ISSUE THREAD

**Issue by OnlyDankan** [Nem-Tudo/betterbluesky_extension#7]
Eu não sei se era para estar assim, mas eu acho que a colocação dos lugares (primeiro, segundo, terceiro e etc) deveria ser por quantidade de posts, aqui está um exemplo do erro que está ocorrendo: 
![WhatsApp Image 2024-09-05 at 17 10 20](https://github.com/user-attachments/assets/31b7cb1c-8961-4bd1-b0bc-92c9b778b548)

O primeiro colocado está com menos posts sobre o assunto e está acima do segundo colocado que tem muito mais

**Comment by rafabd1** [comment]
mandei um PR no repositorio da api adicionando uma função pra reordenar os trends por n° de posts https://github.com/Nem-Tudo/betterbluesky_api/pull/1

**Comment by fabiohcnobre** [comment]
Ficou legal parabens!
